blank_issues_enabled: true
contact_links:
  - name: 💬 主题交流群（QQ）
    url: https://qm.qq.com/q/onMpJjYvgQ
    about: 使用过程中的疑问可以在交流群中讨论
  - name: 🧩 Halo 应用市场
    url: https://www.halo.run/store/apps/app-zqvrlonl
    about: 前往应用市场安装 / 更新主题
